// app/layout.tsx
import type { Metadata } from "next";
//import { Inter } from "next/font/google";
import { Plus_Jakarta_Sans } from 'next/font/google';
import "./globals.css";
import Sidebar from "@/components/Sidebar";

//const inter = Inter({ subsets: ["latin"] });
const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin', 'vietnamese'], // Hỗ trợ tiếng Việt
  weight: ['400', '500', '600', '700', '800'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "PETRUS KY",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="vi">
      <body className={`${plusJakartaSans.className} h-screen overflow-hidden`}>
        <div className="flex h-full bg-gray-100">
          <Sidebar />

          {/* MAIN CONTENT */}
          <div className="flex-1 min-w-0">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
